"""add attendance calculations

Revision ID: 1671b1d8f0c8
Revises: 8b711cbc6439
Create Date: 2026-09-28 14:38:55.311604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1671b1d8f0c8'
down_revision: Union[str, Sequence[str], None] = '8b711cbc6439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'attendances',
    sa.Column(
        'late_minutes',
        sa.Integer(),
        nullable=False,
        server_default='0',
    )
)
    op.add_column(
    'attendances',
    sa.Column(
        'working_minutes',
        sa.Integer(),
        nullable=False,
        server_default='0',
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'working_minutes')
    op.drop_column('attendances', 'late_minutes')
    # ### end Alembic commands ###
