"""add attendance

Revision ID: 3c32fdb07b72
Revises: ce3ccaf55d4d
Create Date: 2026-09-28 11:37:31.847095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c32fdb07b72'
down_revision: Union[str, Sequence[str], None] = 'ce3ccaf55d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_attendance_date'), 'attendances', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendances_employee_id'), 'attendances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendances_organization_id'), 'attendances', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendances_organization_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_employee_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_attendance_date'), table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###
