"""add_core_hr_employee_architecture

Revision ID: d16a1912264b
Revises: 94c360fe81be
Create Date: 2026-10-03 15:59:14.413564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd16a1912264b'
down_revision: Union[str, Sequence[str], None] = '94c360fe81be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_department_id'), 'teams', ['department_id'], unique=False)
    op.create_index(op.f('ix_teams_manager_id'), 'teams', ['manager_id'], unique=False)
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_table('employee_bank_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_holder_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('ifsc_code', sa.String(length=30), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_bank_details_employee_id'), 'employee_bank_details', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_bank_details_organization_id'), 'employee_bank_details', ['organization_id'], unique=False)
    op.create_table('employee_dependents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_dependent', sa.Boolean(), nullable=False),
    sa.Column('is_nominee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_dependents_employee_id'), 'employee_dependents', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_dependents_organization_id'), 'employee_dependents', ['organization_id'], unique=False)
    op.create_table('employee_educations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('start_year', sa.String(length=20), nullable=True),
    sa.Column('end_year', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_educations_employee_id'), 'employee_educations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_educations_organization_id'), 'employee_educations', ['organization_id'], unique=False)
    op.create_table('employee_emergency_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('alternate_phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_emergency_contacts_employee_id'), 'employee_emergency_contacts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_emergency_contacts_organization_id'), 'employee_emergency_contacts', ['organization_id'], unique=False)
    op.create_table('employee_experiences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('last_drawn_salary', sa.Float(), nullable=True),
    sa.Column('reason_for_leaving', sa.Text(), nullable=True),
    sa.Column('document_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_experiences_employee_id'), 'employee_experiences', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_experiences_organization_id'), 'employee_experiences', ['organization_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.String(length=30), nullable=False),
    sa.Column('years_of_experience', sa.Float(), nullable=True),
    sa.Column('certification_name', sa.String(length=200), nullable=True),
    sa.Column('certification_expiry', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_skills_employee_id'), 'employee_skills', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_organization_id'), 'employee_skills', ['organization_id'], unique=False)
    op.create_table('employee_statutory_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('pan_number', sa.String(length=20), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('uan_number', sa.String(length=30), nullable=True),
    sa.Column('pf_number', sa.String(length=50), nullable=True),
    sa.Column('esi_number', sa.String(length=50), nullable=True),
    sa.Column('professional_tax_state', sa.String(length=50), nullable=True),
    sa.Column('tax_regime', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_statutory_details_employee_id'), 'employee_statutory_details', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employee_statutory_details_organization_id'), 'employee_statutory_details', ['organization_id'], unique=False)
    op.create_table('employee_employment_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_employment_history_employee_id'), 'employee_employment_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_employment_history_organization_id'), 'employee_employment_history', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_resignations_employee_id'), table_name='resignations')
    op.drop_index(op.f('ix_resignations_organization_id'), table_name='resignations')
    op.drop_index(op.f('ix_resignations_status'), table_name='resignations')
    op.drop_table('resignations')
    op.alter_column('attendance_regularizations', 'rejection_reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_attendance_regularizations_attendance_date'), table_name='attendance_regularizations')
    op.drop_index(op.f('ix_attendance_regularizations_status'), table_name='attendance_regularizations')
    op.add_column('employees', sa.Column('team_id', sa.Uuid(), nullable=True))
    op.add_column('employees', sa.Column('hr_manager_id', sa.Uuid(), nullable=True))
    op.add_column('employees', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('preferred_name', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('profile_photo_url', sa.String(length=500), nullable=True))
    op.add_column('employees', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('personal_email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('work_email', sa.String(length=255), nullable=True))
    op.add_column('employees', sa.Column('personal_phone', sa.String(length=30), nullable=True))
    op.add_column('employees', sa.Column('work_phone', sa.String(length=30), nullable=True))
    op.add_column('employees', sa.Column('current_address', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('current_city', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('current_state', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('current_country', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('current_pincode', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('permanent_address', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('permanent_city', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('permanent_state', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('permanent_country', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('permanent_pincode', sa.String(length=20), nullable=True))
    op.add_column('employees', sa.Column('current_same_as_permanent', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('confirmation_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('work_location', sa.String(length=100), nullable=True))
    op.add_column('employees', sa.Column('weekly_off', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('notice_period_days', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('probation_period_days', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('probation_end_date', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('last_working_day', sa.Date(), nullable=True))
    op.alter_column('employees', 'pan_number',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('employees', 'aadhar_number',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_employees_hr_manager_id'), 'employees', ['hr_manager_id'], unique=False)
    op.create_index(op.f('ix_employees_team_id'), 'employees', ['team_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'employees', ['hr_manager_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'teams', ['team_id'], ['id'])
    op.drop_index(op.f('ix_leaves_leave_type_id'), table_name='leaves')
    op.drop_constraint(op.f('fk_leaves_leave_type_id'), 'leaves', type_='foreignkey')
    op.drop_column('leaves', 'is_half_day')
    op.drop_column('leaves', 'half_day_session')
    op.drop_column('leaves', 'rejection_reason')
    op.drop_column('leaves', 'leave_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaves', sa.Column('leave_type_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('rejection_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('half_day_session', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('leaves', sa.Column('is_half_day', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_leaves_leave_type_id'), 'leaves', 'leave_types', ['leave_type_id'], ['id'])
    op.create_index(op.f('ix_leaves_leave_type_id'), 'leaves', ['leave_type_id'], unique=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'employees', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_team_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_hr_manager_id'), table_name='employees')
    op.alter_column('employees', 'aadhar_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('employees', 'pan_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_column('employees', 'last_working_day')
    op.drop_column('employees', 'probation_end_date')
    op.drop_column('employees', 'probation_period_days')
    op.drop_column('employees', 'notice_period_days')
    op.drop_column('employees', 'weekly_off')
    op.drop_column('employees', 'work_location')
    op.drop_column('employees', 'confirmation_date')
    op.drop_column('employees', 'current_same_as_permanent')
    op.drop_column('employees', 'permanent_pincode')
    op.drop_column('employees', 'permanent_country')
    op.drop_column('employees', 'permanent_state')
    op.drop_column('employees', 'permanent_city')
    op.drop_column('employees', 'permanent_address')
    op.drop_column('employees', 'current_pincode')
    op.drop_column('employees', 'current_country')
    op.drop_column('employees', 'current_state')
    op.drop_column('employees', 'current_city')
    op.drop_column('employees', 'current_address')
    op.drop_column('employees', 'work_phone')
    op.drop_column('employees', 'personal_phone')
    op.drop_column('employees', 'work_email')
    op.drop_column('employees', 'personal_email')
    op.drop_column('employees', 'nationality')
    op.drop_column('employees', 'profile_photo_url')
    op.drop_column('employees', 'preferred_name')
    op.drop_column('employees', 'middle_name')
    op.drop_column('employees', 'hr_manager_id')
    op.drop_column('employees', 'team_id')
    op.create_index(op.f('ix_attendance_regularizations_status'), 'attendance_regularizations', ['status'], unique=False)
    op.create_index(op.f('ix_attendance_regularizations_attendance_date'), 'attendance_regularizations', ['attendance_date'], unique=False)
    op.alter_column('attendance_regularizations', 'rejection_reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_table('resignations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resignation_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('proposed_last_working_day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notice_period_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('final_last_working_day', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('exit_interview_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('clearance_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('asset_returned', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('final_settlement_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('resignations_employee_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('resignations_organization_id_fkey')),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('resignations_reviewed_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resignations_pkey'))
    )
    op.create_index(op.f('ix_resignations_status'), 'resignations', ['status'], unique=False)
    op.create_index(op.f('ix_resignations_organization_id'), 'resignations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resignations_employee_id'), 'resignations', ['employee_id'], unique=False)
    op.drop_index(op.f('ix_employee_employment_history_organization_id'), table_name='employee_employment_history')
    op.drop_index(op.f('ix_employee_employment_history_employee_id'), table_name='employee_employment_history')
    op.drop_table('employee_employment_history')
    op.drop_index(op.f('ix_employee_statutory_details_organization_id'), table_name='employee_statutory_details')
    op.drop_index(op.f('ix_employee_statutory_details_employee_id'), table_name='employee_statutory_details')
    op.drop_table('employee_statutory_details')
    op.drop_index(op.f('ix_employee_skills_organization_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_employee_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_employee_experiences_organization_id'), table_name='employee_experiences')
    op.drop_index(op.f('ix_employee_experiences_employee_id'), table_name='employee_experiences')
    op.drop_table('employee_experiences')
    op.drop_index(op.f('ix_employee_emergency_contacts_organization_id'), table_name='employee_emergency_contacts')
    op.drop_index(op.f('ix_employee_emergency_contacts_employee_id'), table_name='employee_emergency_contacts')
    op.drop_table('employee_emergency_contacts')
    op.drop_index(op.f('ix_employee_educations_organization_id'), table_name='employee_educations')
    op.drop_index(op.f('ix_employee_educations_employee_id'), table_name='employee_educations')
    op.drop_table('employee_educations')
    op.drop_index(op.f('ix_employee_dependents_organization_id'), table_name='employee_dependents')
    op.drop_index(op.f('ix_employee_dependents_employee_id'), table_name='employee_dependents')
    op.drop_table('employee_dependents')
    op.drop_index(op.f('ix_employee_bank_details_organization_id'), table_name='employee_bank_details')
    op.drop_index(op.f('ix_employee_bank_details_employee_id'), table_name='employee_bank_details')
    op.drop_table('employee_bank_details')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_manager_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_department_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
