"""add shift to employees

Revision ID: e83b7834dcb7
Revises: 0a5f64fc8176
Create Date: 2026-09-28 12:13:39.959580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83b7834dcb7'
down_revision: Union[str, Sequence[str], None] = '0a5f64fc8176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('shift_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_employees_shift_id'), 'employees', ['shift_id'], unique=False)
    op.create_foreign_key(None, 'employees', 'shifts', ['shift_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_shift_id'), table_name='employees')
    op.drop_column('employees', 'shift_id')
    # ### end Alembic commands ###
