import { useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import { Check, Plus, X } from "lucide-react";
import { approveLeave, createLeave, getLeaves, rejectLeave, type Leave as LeaveRecord } from "../api/leaves";
import { getEmployees, type Employee } from "../api/employees";

export default function Leave() {
  const [leaves,setLeaves]=useState<LeaveRecord[]>([]);
  const [employees,setEmployees]=useState<Employee[]>([]);
  const [open,setOpen]=useState(false);
  const [error,setError]=useState("");
  const [form,setForm]=useState({employee_id:"",leave_type:"Sick",start_date:"",end_date:"",reason:""});
  async function load(){try{const [l,e]=await Promise.all([getLeaves(),getEmployees()]);setLeaves(l);setEmployees(e);setError("")}catch(err:any){setError(err?.response?.data?.detail??"Failed to load leave requests.")}}
  useEffect(()=>{void load()},[]);
  const names=useMemo(()=>new Map(employees.map(e=>[e.id,`${e.first_name} ${e.last_name??""}`.trim()])),[employees]);
  async function submit(e:FormEvent){e.preventDefault();try{await createLeave({...form,reason:form.reason||null});setOpen(false);setForm({employee_id:"",leave_type:"Sick",start_date:"",end_date:"",reason:""});await load()}catch(err:any){setError(err?.response?.data?.detail??"Unable to create leave.")}}
  async function action(id:string,type:"approve"|"reject"){try{type==="approve"?await approveLeave(id):await rejectLeave(id);await load()}catch(err:any){setError(err?.response?.data?.detail??"Unable to update leave.")}}
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="text-3xl font-bold">Leave Management</h2><p className="mt-1 text-sm text-slate-500">{leaves.filter(l=>l.status==="pending").length} pending requests</p></div><button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-sm font-semibold text-white"><Plus size={18}/> New leave</button></div>
    {error&&<div className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">{error}</div>}
    <div className="rounded-2xl border border-slate-200 bg-white overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr>{["Employee","Type","Start","End","Reason","Status","Actions"].map(x=><th key={x} className="px-5 py-4">{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{leaves.length===0?<tr><td colSpan={7} className="px-5 py-12 text-center text-sm text-slate-400">No leave requests.</td></tr>:leaves.map(l=><tr key={l.id}><td className="px-5 py-4 text-sm font-medium">{names.get(l.employee_id)??l.employee_id.slice(0,8)}</td><td className="px-5 py-4 text-sm">{l.leave_type}</td><td className="px-5 py-4 text-sm">{l.start_date}</td><td className="px-5 py-4 text-sm">{l.end_date}</td><td className="px-5 py-4 text-sm">{l.reason??"—"}</td><td className="px-5 py-4"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${l.status==="approved"?"bg-emerald-50 text-emerald-600":l.status==="rejected"?"bg-red-50 text-red-600":"bg-amber-50 text-amber-600"}`}>{l.status}</span></td><td className="px-5 py-4">{l.status==="pending"&&<div className="flex gap-2"><button onClick={()=>void action(l.id,"approve")} className="rounded-lg p-2 text-emerald-600 hover:bg-emerald-50"><Check size={17}/></button><button onClick={()=>void action(l.id,"reject")} className="rounded-lg p-2 text-red-500 hover:bg-red-50"><X size={17}/></button></div>}</td></tr>)}</tbody></table></div>
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div className="flex justify-between"><h3 className="text-xl font-bold">New leave request</h3><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="mt-5 space-y-4"><label className="block text-sm font-medium">Employee<select required value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"><option value="">Select employee</option>{employees.filter(e=>e.employment_status==="active").map(e=><option key={e.id} value={e.id}>{`${e.first_name} ${e.last_name??""}`.trim()}</option>)}</select></label><label className="block text-sm font-medium">Leave type<select value={form.leave_type} onChange={e=>setForm({...form,leave_type:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"><option>Sick</option><option>Casual</option><option>Annual</option><option>Emergency</option></select></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">Start<input required type="date" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label><label className="block text-sm font-medium">End<input required type="date" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label></div><label className="block text-sm font-medium">Reason<textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" rows={3}/></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border px-4 py-2.5">Cancel</button><button className="rounded-xl bg-indigo-600 px-5 py-2.5 font-semibold text-white">Create request</button></div></form></div>}
  </div>
}
